# Generated by Django 4.2.7 on 2023-11-13 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_seats', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.warehouse')),
            ],
        ),
    ]
