# Generated by Django 4.2.7 on 2023-11-13 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('location', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confectionary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=255)),
                ('expiration_date', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('calory', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('customers', models.ManyToManyField(to='customer.customer')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.manufacturer')),
                ('warehouses', models.ManyToManyField(to='warehouse.warehouse')),
            ],
        ),
    ]
